project:
  type: website

website:
  title: "Glossário de Clima e Saúde"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - equipe.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

lang: pt-BR

