---
title: "Acordo de Paris"
---

## Definição

O Acordo de Paris é um tratado internacional juridicamente vinculativo sobre as alterações climáticas. Foi adotado por 195 Partes na Conferência das Nações Unidas sobre as Mudanças Climáticas (COP21), em Paris, França, a 12 de dezembro de 2015, e entrou em vigor a 4 de novembro de 2016. Atualmente, a partir de 27 de janeiro de 2026, o Acordo de Paris conta com 194 Partes. O seu objetivo primordial é manter o aumento da temperatura média global bem abaixo de 2 °C acima dos níveis pré-industriais e envidar esforços para limitar o aumento da temperatura a 1,5 °C acima dos níveis pré-industriais.

## Texto original

> "The Paris Agreement is a legally binding international treaty on climate change. It was adopted by 195 Parties at the UN Climate Change Conference (COP21) in Paris, France, on 12 December 2015. It entered into force on 4 November 2016. Currently, as of 27 January 2026, there are 194 Parties to the Paris Agreement.
>
> Its overarching goal is to hold “the increase in the global average temperature to well below 2°C above pre-industrial levels” and pursue efforts “to limit the temperature increase to 1.5°C above pre-industrial levels."

## Fonte

https://unfccc.int/process-and-meetings/the-paris-agreement
