---
title: "Agricultura Regenerativa"
subtitle: "Regenerative Agriculture"
---

## Definição

A agricultura regenerativa é uma forma de cultivo que nutre e restaura a saúde do solo e, portanto, reduz o uso de água, previne a degradação da terra e promove a biodiversidade. Ao minimizar o revolvimento do solo, praticar a rotação de culturas e usar esterco animal e composto, a agricultura regenerativa garante que o solo armazene mais carbono, conserve mais umidade e seja mais saudável devido às prósperas comunidades de fungos.

A agricultura intensiva é responsável por um terço das emissões globais de gases de efeito estufa, utiliza 70% da água doce que consumimos e leva à degradação do solo por meio do uso de máquinas pesadas, fertilizantes químicos e pesticidas. É também a maior contribuinte para a perda de biodiversidade. Em contrapartida, a agricultura regenerativa ajuda a reduzir as emissões de gases de efeito estufa, conserva a água e restaura a terra. Além disso, um solo saudável produz mais alimentos e melhor nutrição e tem outros impactos positivos nos ecossistemas e na biodiversidade.

## Texto original

> Regenerative agriculture is a way of farming that nurtures and restores soil health, and therefore reduces water use, prevents land degradation, and promotes biodiversity. By minimizing land ploughing, practicing rotating crops, and using animal manure and compost, regenerative agriculture ensures that the soil stores more carbon, conserves more moisture, and is healthier due to thriving fungal communities.

Intensive agriculture is responsible for a third of global greenhousegas emissions, uses 70 percent of the fresh water we consume, and leads to soil degradation through its use of heavy machinery, chemical fertilizers, and pesticides. It is also the biggest contributor to biodiversity loss. By contrast, regenerative agriculture helps lower greenhouse gas emissions, conserves water, and restores land. Moreover, healthy soil produces more food and better nutrition and has other positive impacts on ecosystems and biodiversity.

## Fonte

UNDP. The Climate Dictionary. New York: ONU, 2023.