---
title: "Avaliação de Impacto Ambiental"
---

## Definição

1. Procedimento destinado à avaliação dos impactos ambientais provocados a partir de um processo ou projeto a ser implantado. 2. Exame, análise e avaliação de atividades e processos planejados, com o objetivo de garantir um desenvolvimento adequado e que não cause prejuízo ao meio ambiente. 3. Instrumento multidisciplinar que busca identificar os interesses ambientais, os riscos de degradação e deterioração dos recursos físicos e os impactos sobre a flora e a fauna e sobre a saúde humana. Dá origem a um Relatório de Impacto Ambiental (RIMA) que, para ser útil, deve ser difundido em termos compreensíveis pela população e pelos que decidirão a respeito. Os aspectos positivos e negativos devem ser identificados à base de critérios realmente relevantes para as comunidades afetadas.

## Texto original

> -

## Fonte

Glossário de Defesa Civil: estudos de Riscos e Medicina de Desastres. CASTRO, Antonio Luiz Coimbra de. 5. ed. Brasília – DF: Secretaria Nacional de Defesa Civil (SEDEC), 2009.
