---
title: "Empregos Verdes"
subtitle: "Green Jobs"
---

## Definição

Empregos verdes são empregos dignos que contribuem para a proteção e restauração do meio ambiente e para o combate às mudanças climáticas. Eles podem ser encontrados tanto na produção de produtos e serviços verdes, como energia renovável, quanto em processos ecologicamente corretos, como a reciclagem. Os empregos verdes ajudam a melhorar a eficiência energética e de matérias-primas, limitar as emissões de gases de efeito estufa, minimizar o desperdício e a poluição, proteger e restaurar ecossistemas e apoiar a adaptação aos impactos das mudanças climáticas.

## Texto original

> Green jobs are decent jobs that contribute to protecting and restoring the environment and addressing climate change. Green jobs can be found in both the production of green products and services, such as renewable energy, and in environmentally friendly processes, such as recycling. Green jobs help improve energy and raw material efficiency, limit greenhouse gas emissions, minimize waste and pollution, protect and restore ecosystems, and support adaptation to the impacts of climate change.

## Fonte

UNDP. The Climate Dictionary. New York: ONU, 2023.