---
title: "Equidade"
---

## Definição

O princípio de ser justo e imparcial, e uma base para compreender como os impactos e as respostas às mudanças climáticas, incluindo custos e benefícios, são distribuídos na sociedade e por ela de maneiras mais ou menos equitativas. Frequentemente associado às ideias de igualdade, equidade e justiça, e aplicado no que diz respeito à responsabilidade pelos impactos climáticos e às políticas relacionadas, bem como à sua distribuição na sociedade, entre gerações e entre gêneros, e também no sentido de quem participa e controla os processos de tomada de decisão.

## Texto original

> "The principle of being fair and impartial, and a basis for understanding how the impacts and responses to climate change, including costs and benefits, are distributed in and by society in more or less equal ways. Often aligned with ideas of equality, fairness and justice and applied with respect to equity in the responsibility for, and distribution of, climate impacts and policies across society, generations and gender, and in the sense of who participates and controls the processes of decision-making."

## Fonte

IPCC, AR6 Working Group II – Annex II: Glossary, 2022, p. 2927
