---
title: "Greenwashing"
---

## Definição

O greenwashing — ou lavagem verde, em português — é uma estratégia de marketing comum e ilusória na qual empresas promovem seus produtos como ambientalmente responsáveis sem cumprir os critérios reais de sustentabilidade.

O greenwashing representa um obstáculo significativo no combate às mudanças climáticas. Ao induzir o público a acreditar que uma empresa ou outra entidade está fazendo mais para proteger o meio ambiente do que realmente está, o greenwashing promove falsas soluções para a crise climática, desviando a atenção e atrasando ações concretas e confiáveis.

## Texto original

> Greenwashing presents a significant obstacle to tackling climate change. By misleading the public to believe that a company or other entity is doing more to protect the environment than it is, greenwashing promotes false solutions to the climate crisis that distract from and delay concrete and credible action.

## Fonte

[Ministério da Justiça e Segurança Pública](https://www.gov.br/mj/pt-br/assuntos/noticias/greenwashing-entenda-o-que-e-e-aprenda-a-se-defender-de-propagandas-falsas)
[United Nations - Climate Action](https://www.un.org/en/climatechange/science/climate-issues/greenwashing)