---
title: "Justiça climática"
subtitle: "Climate justice"
---

## Definição

Justiça climática vincula direitos humanos e desenvolvimento a uma abordagem centrada nas pessoas, protegendo os direitos dos mais vulneráveis e compartilhando, de forma equitativa e justa, os encargos e benefícios das mudanças climáticas e seus impactos.

## Texto original

> "Climate justice means putting equity and human rights at the core of decision-making and action on climate change. The concept has been widely used to refer to the unequal historical responsibility that countries and communities bear in relation to the climate crisis. It suggests that the countries, industries, businesses, and people that have become wealthy from emitting large amounts of greenhouse gases have a responsibility to help those affected by climate change, particularly the most vulnerable countries and communities, who often are the ones that have contributed the least to the crisis."

## Fonte

United Nations Development Program (UNDP). Climate change is a matter of justice - here's why. 2023.
