---
title: "Renaturalização"
subtitle: "Rewilding"
---

## Definição

Renaturalização é a restauração em massa de ecossistemas que foram danificados pela atividade humana. Mais do que conservação, que se concentra em salvar espécies específicas por meio de intervenção humana dedicada, a renaturalização refere-se à preservação de grandes áreas para que o mundo natural se regenere por si só. Isso às vezes requer a reintrodução de espécies-chave que foram extintas em uma determinada região, como castores, lobos ou grandes herbívoros, que ajudam a moldar ecossistemas inteiros.

A renaturalização pode ajudar a combater as mudanças climáticas, removendo mais dióxido de carbono da atmosfera por meio de processos naturais saudáveis, como a regeneração natural de florestas. Também ajuda a prevenir a extinção de espécies, criando habitats ricos em natureza que permitem que a vida selvagem se adapte às mudanças climáticas e migre à medida que o aquecimento se intensifica.

## Texto original

> Rewilding is the mass restoration of ecosystems that have been damaged by human activity. More than conservation, which focuses on saving specific species through dedicated human intervention, rewilding refers to setting aside large areas for the natural world to regenerate in on its own terms. This sometimes requires there introduction of key species that have been driven extinct in a particular region, such as beavers, wolves, or large herbivores, whohelp shape entire ecosystems.

Rewilding can help combat climate change by removing more carbon dioxide from the atmosphere through healthy natural processes such as natural woodland regeneration. It also helps prevent species extinction by creating nature-rich habitats that allow wildlife to adapt to climate change and migrate as warming intensifies.

## Fonte

UNDP. The Climate Dictionary. New York: ONU, 2023.