---
title: "Seca"
---

## Definição

Um período excepcional de falta de água para os ecossistemas e a população humana (devido a baixa precipitação, alta temperatura e/ou vento).

1. Ausência prolongada, deficiência acentuada ou fraca distribuição de precipitação. 2. Período de tempo seco, suficientemente prolongado, para que a falta de precipitação provoque grave desequilíbrio hidrológico. 3. Do ponto de vista meteorológico, a seca é uma estiagem prolongada, caracterizada por provocar uma redução sustentada das reservas hídricas existentes. 4. Numa visão sócioeconômica, a seca depende muito mais das vulnerabilidades dos grupos sociais afetados que das condições climáticas.

## Texto original

> "An exceptional period of water shortage for existing ecosystems and the human population (due to low rainfall, high temperature and/or wind)."

## Fonte

IPCC, AR6 Working Group II – Annex II: Glossary, 2022, p. 2927

Glossário de Defesa Civil: estudos de Riscos e Medicina de Desastres. CASTRO, Antonio Luiz Coimbra de. 5. ed. Brasília – DF: Secretaria Nacional de Defesa Civil (SEDEC), 2009.
