---
title: "Segurança Climática"
subtitle: "Climate Safety"
---

## Definição

Segurança climática refere-se à avaliação, gestão e redução dos riscos à paz e à estabilidade causados ​​pela crise climática. Isso significa garantir que a mitigação e a adaptação às mudanças climáticas vão além da simples não ocorrência de danos e contribuam positivamente para a paz e a estabilidade. Significa também que as intervenções de prevenção de conflitos e construção da paz levem em consideração os impactos climáticos. As soluções técnicas para a ação e a adaptação às mudanças climáticas podem servir como oportunidades para construir a paz e reconstruir o tecido social, especialmente em países afetados por conflitos e fragilidade.

## Texto original

> Climate security refers to evaluating, managing, and reducing the risks to peace and stability brought on by the climate crisis. This means ensuring that climate mitigation and adaptation goes beyond doing no harm and contributes positively to peace and stability. It also means that conflict prevention and peace building interventions take climate impacts into account. The technical solutions to climate action and adaptation can serve as opportunities to build peace and mend the social fabric, especially in countries affected by conflict and fragility.

## Fonte

UNDP. The Climate Dictionary. New York: ONU, 2023.