---
title: "Serviços ecossistêmicos"
---

## Definição

Processos ou funções ecológicas que possuem valor monetário ou não monetário para indivíduos ou para a sociedade em geral. Estes são frequentemente classificados como (1) serviços de suporte, como produtividade ou manutenção da biodiversidade, (2) serviços de provisão, como alimentos ou fibras, (3) serviços de regulação, como regulação climática ou sequestro de carbono e (4) serviços culturais, como turismo ou apreciação espiritual e estética.

## Texto original

> "Ecological processes or functions having monetary or non-monetary value to individuals or society at large. These are frequently classified as (1) supporting services such as productivity or biodiversity maintenance, (2) provisioning services such as food or fibre, (3) regulating services such as climate regulation or carbon sequestration and (4) cultural services such as tourism or spiritual and aesthetic appreciation."

## Fonte

IPCC, AR6 Working Group II – Annex II: Glossary, 2022, p. 2927
