---
title: "Transição justa"
---

## Definição

Um conjunto de princípios, processos e práticas que visam garantir que nenhuma pessoa, trabalhador, lugar, setor, país ou região seja deixado para trás na transição de uma economia de alto carbono para uma economia de baixo carbono. Enfatiza a necessidade de medidas direcionadas e proativas por parte de governos, agências e autoridades para garantir que quaisquer impactos sociais, ambientais ou econômicos negativos das transições em toda a economia sejam minimizados, enquanto os benefícios são maximizados para aqueles desproporcionalmente afetados. Os princípios-chave das transições justas incluem: respeito e dignidade para os grupos vulneráveis; equidade no acesso e uso da energia; diálogo social e consulta democrática com as partes interessadas relevantes; a criação de empregos decentes; proteção social; e direitos no trabalho. Transições justas podem incluir equidade nos processos de planejamento e tomada de decisão em energia, uso da terra e clima; diversificação econômica baseada em investimentos de baixo carbono; programas realistas de treinamento/requalificação que levem a trabalho decente; políticas específicas de gênero que promovam resultados equitativos; o fomento da cooperação internacional e ações multilaterais coordenadas; e a erradicação da pobreza. Por fim, as transições justas podem incorporar a reparação de danos passados ​​e injustiças percebidas.

## Texto original

> "A set of principles, processes and practices that aim to ensure that no people, workers, places, sectors, countries or regions are left behind in the transition from a high-carbon to a low-carbon economy. It stresses the need for targeted and proactive measures from governments, agencies and authorities to ensure that any negative social, environmental or economic impacts of economy-wide transitions are minimised, while benefits are maximised for those disproportionally affected. Key principles of just transitions include: respect and dignity for vulnerable groups; fairness in energy access and use, social dialogue and democratic consultation with relevant stakeholders; the creation of decent jobs; social protection; and rights at work. Just transitions could include fairness in energy, land use and climate planning and decision-making processes; economic diversification based on low-carbon investments; realistic training/retraining programs that lead to decent work; gender-specific policies that promote equitable outcomes; the fostering of international cooperation and coordinated multilateral actions; and the eradication of poverty. Lastly, just transitions may embody the redressing of past harms and perceived injustices"

## Fonte

ILO. Guidelines for a just transition towards environmentally sustainable economies and societies for all. 2015, p. 6.
IPCC, AR6 Working Group II – Annex II: Glossary, 2022, p. 2927
UNFCCC. Just transition of the workforce, and the creation of decent work and quality jobs. 2016.
