---
title: "Transparência"
subtitle: "Transparency"
---

## Definição

Nos termos do Acordo de Paris, os países devem apresentar relatórios regulares sobre a implementação de suas Contribuições Nacionalmente Determinadas. É crucial que esses relatórios sejam feitos com transparência para permitir que a comunidade global avalie com precisão o progresso coletivo e construa a confiança de que todos estão fazendo a sua parte.

Relatórios transparentes permitem que governos e organismos internacionais tenham acesso a dados confiáveis ​​e tomem decisões baseadas em evidências. Também aprimoram nossa compreensão científica das mudanças climáticas e das ações e políticas necessárias para mitigá-las e nos adaptar aos seus impactos. Em última análise, a transparência é fundamental para desbloquear todo o potencial do Acordo de Paris, promovendo confiança, colaboração e transferência de conhecimento e incentivando uma maior ambição em relação às metas climáticas.

## Texto original

> Under the Paris Agreement, countries must regularly report on the implementation of their Nationally Determined Contributions. It is crucial that this reporting is done with transparency to allow the global community to accurately assess collective progress and build trust that everyone is playing their part.

Transparent reporting allows governments and international bodies to have access to reliable data and make evidence-based decisions. It also enhances our scientific understanding of climate change and the actions and policies needed to mitigate it and adapt to its impacts. Ultimately, transparency is key to unlocking the full potential of the Paris Agreement, by promoting trust, collaboration and knowledge transfer and encouraging further ambition on climate targets.

## Fonte

UNDP. The Climate Dictionary. New York: ONU, 2023.